CREATE DATABASE HotelManagement
GO
USE HotelManagement
GO

CREATE TABLE ACCOUNT
(
	UserName	VARCHAR(20) NOT NULL PRIMARY KEY,
	Password	VARCHAR(20) NOT NULL,
)

GO
CREATE TABLE ROOM_TYPE												--Loại phòng
(
	RoomTypeId		CHAR(1) NOT NULL PRIMARY KEY,		--QD1--
	PriceByDay		MONEY NOT NULL,
	Price1stHour	MONEY NOT NULL,
	PricePerHour	MONEY NOT NULL,
	Note			NVARCHAR(100)
)												
GO
CREATE TABLE ROOM_STATUS
(
	StatusID	INT IDENTITY NOT NULL PRIMARY KEY,
	StatusName	NVARCHAR(20)
)													
GO
CREATE TABLE FLOOR
(
	FloorId INT IDENTITY PRIMARY KEY,
	FloorName NVARCHAR(10)
)
GO
CREATE TABLE ROOM													--Phòng
(
	RoomId		INT NOT NULL PRIMARY KEY,
	RoomTypeId	CHAR(1),
	Description	NVARCHAR(200),
	NumOfBed	INT,
	PeoPerBed	INT,
	MaxCapacity INT,
	FloorId		INT,
	StatusId	INT 
	FOREIGN KEY (RoomTypeId) REFERENCES ROOM_TYPE(RoomTypeId),
	FOREIGN KEY (StatusId) REFERENCES ROOM_STATUS(StatusId),
	FOREIGN KEY (FloorId) REFERENCES dbo.FLOOR(FloorId)
)
GO
CREATE TABLE NATIONALITY
(
	NatId		INT IDENTITY NOT NULL PRIMARY KEY,
	Name		NVARCHAR(20)
)
CREATE TABLE RENTER														--Người Thuê
(
	RenterId	VARCHAR(20) NOT NULL PRIMARY KEY,
	Name		NVARCHAR(30) NOT NULL,
	Gender		bit NOT NULL,
	PhoneNum	VARCHAR(15),
	NatId		INT,													--QD2--
	IDENTITYNum	VARCHAR(20),
	Address		VARCHAR(40)

	FOREIGN KEY (NatId) REFERENCES NATIONALITY(NatId)
)
GO
CREATE TABLE SERVICE_TYPE
(
	SvTypeId	INT IDENTITY PRIMARY KEY,
	SvTypeName	NVARCHAR(30),
)
GO
CREATE TABLE SERVICE 
(
	ServId	INT IDENTITY PRIMARY KEY,
	Name	VARCHAR(15),
	Price	MONEY NOT NULL DEFAULT 0,
	SvTypeId INT,
	FOREIGN KEY (SvTypeId) REFERENCES SERVICE_TYPE(SvTypeId)
)
GO
CREATE TABLE BILL														--hóa đơn
(
	BillId		VARCHAR(20) NOT NULL PRIMARY KEY,
	RenterId	VARCHAR(20),
	RoomId		INT,
	TotalMoney	MONEY NOT NULL,
	
	FOREIGN KEY (RoomId) REFERENCES ROOM(RoomId),
	FOREIGN KEY (RenterId) REFERENCES RENTER(RenterId),)
GO
CREATE TABLE TABLE_NATIONALITY
(
	NatId	INT IDENTITY PRIMARY KEY,
	NatName NVARCHAR(20)
)
GO
CREATE TABLE REG_FORM														--phiếu thuê phòng
(
	FormId		INT IDENTITY PRIMARY KEY,
	CheckIn		smalldatetime NOT NULL,
	CheckOut	smalldatetime,
	RenterId	VARCHAR(20),
	RoomId		INT,
	BillId		VARCHAR(20),
	NatId		INT,

	FOREIGN KEY (RenterId) REFERENCES RENTER(RenterId),
	FOREIGN KEY (RoomId) REFERENCES ROOM(RoomId),
	FOREIGN KEY (BillId) REFERENCES BILL(BillId),
	FOREIGN KEY (NatId) REFERENCES TABLE_NATIONALITY(NatId)
)
GO
CREATE TABLE USE_SERVICES
(
	ServId	INT,
	FormId	INT,
	Time	DateTime,

	PRIMARY KEY (ServId, FormId),
	FOREIGN KEY (ServId) REFERENCES SERVICE(ServId),
	FOREIGN KEY (FormId) REFERENCES REG_FORM(FormId)
)
GO
CREATE TABLE ROOMMATES
(
	Name	VARCHAR(30),
	NatId	INT,
	FormId	INT,
	RenterId VARCHAR(20),

	PRIMARY KEY (FormId,RenterId),
	FOREIGN KEY (FormId) REFERENCES REG_FORM(FormId),
	FOREIGN KEY (RenterId) REFERENCES RENTER(RenterId),
	FOREIGN KEY (NatId) REFERENCES TABLE_NATIONALITY(NatId)
)
GO
